# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstApp' do

  
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  

  # Pods for FirstApp
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'ZXingObjC', '~> 3.6.4'

end
